brewtiful/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect, current_app
from pprint import pprint
from .forms import PayWithForm, SendToForm
from datetime import datetime
from .models import Product, Order
from . import db
from email_validator import validate_email
import locale
locale.setlocale(locale.LC_ALL, 'en_AU.UTF-8') 
import sys
from flask_wtf.csrf import CSRFProtect
csrf = CSRFProtect()


# GLOBAL VARIABLES 
user_cart = []
cart_total = 0
countries = ['Australia', 'Austria', 'Burkina Faso', 'Comoros', 'Dominican Republic', 'Eswatini', 'Guyana', 'Guinea-Bissau', 'Iceland', 'Jordan', 'Kyrgyzstan', 'Lebanon', 'Liberia', 'Malawi', 'Marshall Islands', 'Mauritania', 'Micronesia', 'Mozambique', 'Nauru', 'Nicaragua', 'Niger', 'Papua New Guinea', 'Saint Lucia', 'Sierra Leone', 'Solomon Islands', 'South Sudan', 'Tajikistan', 'Togo', 'United Kingdom', 'Venezuela', 'Vietnam']
codes = ['+61', '+43', '+226', '+269', '+1-809', '+268', '+592', '+245', '+354', '+962', '+996', '+961', '+231', '+265', '+692', '+222', '+691', '+258', '+674', '+505', '+227', '+675', '+1-758', '+232', '+677', '+211', '+992', '+228', '+44', '+58', '+84']


# create a blueprint
bp = Blueprint('views', __name__)



# route index  
@bp.route('/')
def index():
    products = Product.query.all()
    blends = ['Blend', 'Single Origin']
    tastes = ['Chocolate', 'Citrus', 'Floral']
    origins = ["Australia", "South America", "Central America", "Africa", "Asia"]

    if 'cart_count' not in session:
        session['cart_count'] = 0

    return render_template(
        'index.html', 
        products=products, 
        blends=blends, 
        tastes=tastes, 
        origins=origins
        )


# route /product/<int:product>
@bp.route('/product/<int:product_id>', methods=['GET', 'POST'])
def product_details(product_id):

    product = Product.query.get_or_404(product_id)
    if request.method == 'POST':
        print('product_id :::')
        print(request.form.get('product_id'))
        print('quantity :::')
        print(int(request.form.get('quantity')))

    return render_template('product-details.html', product=product)





# ADD TO CART 
@bp.route('/add_to_cart/<int:product_id>', methods=['POST'])
def add_to_cart(product_id):
    print('ADD TO CART :::')
    try:
        quantity = int(request.form.get('quantity')) # not using these for the assignment. The default quantity is 1
        print('Quantity', quantity)

        # Check for existing order and create if needed
        order = Order.query.get(session.get('order_id'))
        if order is None:
            order = Order(status=False, total_cost=0, date=datetime.now())
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id

        
        # Check if product already exists in order
        if product_id is not None and order is not None:
            product = Product.query.get(product_id)
            print('ORDER DETAILS :::  \n\n\n', order.products)
            if product not in order.products:
              try:
                session['cart_count'] += 1
                order.products.append(product)
                db.session.commit()
                return redirect(url_for('views.cart'))
              except:
                return 'There was an issue adding the item to your basket'
        else:
            flash('Item already in your basket')
            message = str(message)
            flash(message)
    except:
        print(sys.exc_info()[0])
        return 'There was an issue adding the item to your basket'

    return redirect(url_for('views.product_details', product_id=product_id))






# # CART 
@bp.route('/cart', methods=['GET', 'POST'])
def cart():
    print('\n\nCART :::')
    quantity = 1
    order_id = session.get('order_id')
    cart_list = []
    cart_total = 0

    #  check order exists and display in cart
    if order_id is not None:
        order = Order.query.get_or_404(order_id)
        print('ORDER ::: ', order)

        #  get products from orders to be displayed in cart
        products = {}
        for product in order.products:
            products[product.id] = {
                'id': product.id,
                'name': product.name,
                'price': product.price,
                'image': product.image,
                'quantity': quantity
                }

            #  get total cost of cart
            cart_total = 0
            for product in products.values():
                cart_total += product['price'] * 1 # product['quantity']
            print('CART TOTAL :::  \n\n\n', cart_total)

            # update total cost of order
            order.total_cost = cart_total
            db.session.commit()
            cart_list = list(products.values())
            print(cart_list)

    return render_template('cart.html',
        cart=cart_list, 
        cart_total=locale.currency(cart_total, grouping=True))



# DELETE FROM CART 
@bp.route('/delete_from_cart/<int:product_id>', methods=['GET', 'POST'])
def delete_from_cart(product_id):
    print('\n\nDELETE FROM CART :::')

    # get order from database
    order_id = session.get('order_id')
    order = Order.query.get_or_404(order_id)

    pprint(order.products)

    for product in order.products:
      if product.id == product_id:
            print('PRODUCT WILL BE DELETED')
            session['cart_count'] -= 1
            order.products.remove(product)
            db.session.commit()
            break
      else:
            print(sys.exc_info()[0])
            print('Product failed to delete')

    return redirect(url_for('views.cart'))



# CHECKOUT
@bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    print('\n\nCHECKOUT :::')
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        send_to_form = SendToForm()
        pay_with_form = PayWithForm()
        # Disable all three fields for this assignment as I am not using them
        for field in [pay_with_form.card_number, pay_with_form.expiry, pay_with_form.cvv]:
            field.render_kw = {'disabled': True}

        if request.method == 'POST': # I split my checks here for error handling as it was easier as a beginner to understand
            if send_to_form.validate_on_submit():
                order.status = True
                order.firstname = send_to_form.firstname.data
                order.surname = send_to_form.surname.data
                order.street = send_to_form.street.data
                order.suburb = send_to_form.suburb.data
                order.postcode = send_to_form.postcode.data
                order.country = send_to_form.country.data
                order.email = send_to_form.email.data
                order.phone = send_to_form.phone.data
                order.total_cost = order.total_cost 
                order.date = datetime.now()  

                try:
                    db.session.commit()
                    flash('Thank you! Your order has been submitted successfully.')
                    return redirect(url_for('views.order_completed'))

                except Exception as e:
                    print(f'Error: {e}')
                    return 'There was an issue completing your order.'

        return render_template('checkout.html', 
            cart_total=locale.currency(order.total_cost, grouping=True), 
            user_cart=order.products,
            countries=countries, 
            pay_with_form=pay_with_form, 
            send_to_form=send_to_form,
            codes=codes)




@bp.route('/order-completed', methods=['GET', 'POST'])
def order_completed():
    print(session)
    print('\n\nORDER COMPLETED :::')

    products = []
    address = {}
    order_id = session.get('order_id')
    print('ORDER ID ::: ', order_id)
    if order_id is not None:
        order = Order.query.get_or_404(session['order_id'])
        if order is not None:
            for product in order.products:
                products.append(product)
            
            # get address details 
            address = {
                'firstname': order.firstname,
                'surname': order.surname,
                'street': order.street,
                'suburb': order.suburb,
                'postcode': order.postcode,
                'country': order.country,
                'email': order.email,
                'phone': order.phone
            }

    # in case the user refreshes the page      
    if order_id is None:
       return redirect(url_for('views.index'))
    
    # clear session
    session.clear()

    return render_template('order-completion.html', products=products, address=address, order_id=order_id)




# CLEAR SESSION
@bp.route('/clear_session')
def clear_session():
    session.clear()
    return 'Session cleared!'

brewtiful/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Optional JavaScript -->

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <!-- import index.css file -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">

  <script src="https://kit.fontawesome.com/c13a479c1a.js" crossorigin="anonymous"></script>

  <title>Brewtiful: Best Coffee</title>
  <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='img/favicon.ico')}}">
  <script defer src="{{ url_for('static', filename='js/index.js') }}"></script>
  <script defer src="{{ url_for('static', filename='js/history.js')}}"></script>
</head>

<body >

  <!-- Navigation bar -->
  <div class="black-bar"></div>
  <nav class="navbar navbar-expand-sm justify-content-center ">
    <ul class="navbar-nav flex-row justify-content-between w-100">
      <li class="nav-logo">
        <a  href="{{ url_for('views.index') }}" onclick="userClicksAnchor('/', 'Home')"><img src="{{url_for('static', filename='img/Logo.png') }}"/></a>
      </li>
      <li class="nav-title d-flex align-items-center">
        <div class="our-story">Our Story
          <ul class="nav-title__dropdown">
            <li href="#">About us</li>
            <li href="#">Our first bean</li>
            <li href="#">The factory</li>
            <li href="#">Contact</li>
          </ul>
        </div>
        <div>Brew Guides</div>
      </li>
      <li class="nav-item">
        <div class="nav-item__menu d-flex align-items-center justify-content-center h-100"> 
          <a class="nav-link mx-1 p-0" href="#"><i class="fa-regular fa-user " style="color: #000000;" title="Account" onclick="alert('Button not functional in demo')"></i></a>
          <a class="nav-link mx-1 p-0 position-relative" href="{{ url_for('views.cart') }}" title="Cart" onclick="userClicksAnchor('/cart', 'Cart')"><i class="fa-solid fa-cart-shopping" style="color: #000000;"></i>
            {% if session.get('cart_count', 0) > 0 %}
            <span class="cart-number">
              {{ session.cart_count }}
            </span>
            {% endif %}
          </a>
          <a class="nav-link mx-1 p-0 " href="#"><i class="fa-solid fa-envelope-open-text" style="color: #000000;" title="Messages" onclick="alert('Button not functional in demo')"></i></a>
        </div>
      </li>
    </ul>
  </nav>

  <main>
    {% block content %} {% endblock %}
  </main>

  <!-- Footer -->
  <footer class="footer mt-auto py-3">
    <div class="container">
      <p>&copy; 2023 My 557 site. All rights reserved.</p>
    </div>
  </footer>

</body>
</html>

brewtiful/templates/cart.html
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/cart.css') }}">
  <title>Cart</title>
{% endblock %}

{% extends 'base.html' %}

{% block content %}
  <div class="navbar navbar-expand-sm justify-content-center " >
    <div class="navbar-nav flex-row justify-content-between w-100" id="history">   
      <div id="historyNavigator" ></div>
    </div>
  </div>

  <div class="container mt-5 h-75" style="min-height: 50vh;">
    {% if cart %}
      <div class="row">      
        <div class="col-12">
          <h1>Cart</h1>
    
          <table class="table">
            <thead>
              <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody id="cart-items">
              {% for item in cart %}
                <tr>
                  <td>{{ item.name }} {{item.size}}</td>
                  <td>{{ item.price }}</td>
                  <!-- Add a number select to quantity-->
                  <td>
                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" max="25" class="update-input" disabled onchange="updateCartQuantity(this.form, '{{ item.name }}', this.value)">
                  </td>
                  <td>${{ (item.price | float) * (item.quantity | int)}}</td>
                  <td>  
                    <form action="{{ url_for('views.delete_from_cart', product_id=item.id) }}" method="POST">
                      <input type="submit" value="X" id="delete-btn" >
                    </form>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="d-flex justify-content-end">
            <h3>Total: <span id="total">{{cart_total}}</span></h3>
          </div>
    
        </div>
        <button class="btn  ml-auto mt-4 " id="green-btn"
          onclick="userClicksAnchor('/checkout', 'Checkout')"
        ><a class="w-100 h-100 d-flex justify-content-center align-items-center"  href="{{ url_for('views.checkout') }}"  >Go to payment</a> </button>
      </div>

    {% else %}
      <h3>Your cart is empty</h3>
    {% endif %}

  </div>

  <div class="container-fixed w-100  d-flex flex-grow-1" style="min-height: 100px;">
    <button class="btn btn-success m-auto" id="continue-btn">
      <a class="w-25 h-100 d-flex justify-content-center align-items-center text-white" href="{{ url_for('views.index') }}" onclick="userClicksAnchor('/', 'Home')">
        Continue shopping
      </a>
    </button>
  </div>

{% endblock %}

brewtiful/templates/checkout.html
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/checkout.css') }}">
  <script defer src="{{ url_for('static', filename='js/checkout.js') }}"></script>
  <title>Checkout</title>
{% endblock %}

{% extends 'base.html' %}

{% block content %}
<div class="navbar navbar-expand-sm justify-content-center " >
  <div class="navbar-nav flex-row justify-content-between w-100" id="history">   
    <div id="historyNavigator" ></div>
  </div>
</div>

<form  method="POST" class="container w-100 " id="checkout-container">
  {{ send_to_form.csrf_token }}
  
  <div class="mt-5 checkout-column-one">
    {% include "form-pay-with.html" %}
    {% include "form-send-to.html" %}
    {% include "form-review-checkout.html" %}
  </div>

  <div class="sticky-top w-25 checkout-column-two">

    <div class="sticky-container__inner mt-4 ">
      <div class="sticky-container__inner__items pb-3">
        <div>
          <p><strong>Items:</strong></p>
          <p id="items"><strong>AU {{cart_total}}</strong></p>
        </div>
        <div>
          <p><strong>Postage:</strong></p>
          <p ><strong>Free</strong></p>
        </div>
      </div>

      <div class="sticky-container__inner__total pb-2">
        <h4>Total: </h4>
        <h4 id="total">AU {{cart_total}}</h4>
      </div>

      <div class="sticky-container__inner__checkout pb-4">
        {{ send_to_form.submit(class="btn  ml-auto mt-4 w-100 h-100 d-flex justify-content-center align-items-center", id="confirm-pay") }}
      </div>
    </div>  
  </div>

</form>

{% endblock %}

brewtiful/templates/form-pay-with.html
<div class="checkout-column-block">
  <div class="col-12">
    <div class="title-container">
      <h2>Pay with</h2>
    </div>
    <div class="w-100">
      <div class="form-group">
        {{pay_with_form.card_number(placeholder="Card number", class="form-control", id="card-number") }}
      </div>
      <div class="form-group">
        {{pay_with_form.expiry(placeholder="Expiry", class="form-control", id="expiry") }}
        {{pay_with_form.cvv(placeholder="CVV", class="form-control", id="cvv") }}
      </div>
    </div>
  </div>
</div>

<!-- FORM IS DISABLED IN VIEWS -->

brewtiful/templates/form-review-checkout.html
<div class="checkout-column-block">
  <div class="col-12 ">
    
    <div class="title-container">
      <h2>Review items and postage</h2>
    </div>

    {% for product in user_cart %}
    <div class="d-flex mb-4 pb-4 review-product">
      <div class="">
        <img src="{{ url_for('static', filename=product.image) }}" alt="product image" class="img-fluid review-img">
      </div>
      <div class="review-text">
        <div class="row mb-4">
          <div class="col-6">
            <p>{{product.name}}</p> <!-- This all needs to be a for looop-->
            <p><span id="price"><strong>AU {{product.price }}</strong></span></p> <!-- make currecy format-->
            <p>Quantity: 1</p>
          </div>
        </div>
        

        <div class="col-10 " > <!-- <#miss the first column here.  -->
          <p class="mb-0"><strong>Postage</strong></p>
          <p class="mb-0"><span id="postage">Free postage</span></p>
          <p class="mb-0">Get it by 15 - 20 Dec</p>
          <p>Standard Parcel Delivery</p>
        </div>
      </div>
    </div>
    {% endfor %}

    </div>
  </div>
</div>

brewtiful/templates/form-send-to.html
<div class="checkout-column-block">
  <div class="col-12">

    <div class="title-container">
      <h2>Send to</h2>
    </div>

    <div class="w-100">

      <div class="form-group">
        {{send_to_form.firstname(placeholder="First name", class="form-control", id="first-name") }}
        {{send_to_form.surname(placeholder="Last name", class="form-control", id="last-name") }}
      </div>

      <div class="form-group">
        {{send_to_form.street(placeholder="Street address", class="form-control", id="street-address") }}
      </div>

      <div class="form-group">
        {{send_to_form.suburb(placeholder="Suburb", class="form-control", id="suburb") }}
        {{send_to_form.postcode(placeholder="Postcode", class="form-control", id="postcode") }} 
      </div>

      <div class="form-group">
      <label for="{{ send_to_form.country.id }}"></label>
      {{ send_to_form.country(class="form-control col-4", placeholder="Country", id=send_to_form.country.id) }}
        {{send_to_form.email(placeholder="Email", class="form-control col-8", id="email") }}
      </div>

      <div class="form-group">
        <!-- <select class="form-control col-2" id="country-code" name="country-code">
          <option value="">+61</option>
          <option value=""></option>
          {% for code in codes %}
            <option value="{{ code }}">{{ code }}</option>
          {% endfor %}
        </select>   -->
        {{send_to_form.phone(placeholder="Phone number", class="form-control col-10", id="phone-number") }}
      </div>

    </div>
  </div>
</div>  

brewtiful/templates/index.html
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}"> 
{% endblock %} 

{% extends 'base.html' %}

{% block content %}

  <!-- Hero image and heading -->
  <div class="jumbotron d-flex justify-content-center p-0 mb-2">
    <div class="jumbotron-wrapper d-flex justify-content-center align-items-center w-100 text-center">
        <img src="{{ url_for('static', filename='img/banner.webp')}}" alt="coffee beans in a bag" class="responsive-image">
    </div>
  </div>

  <div class="navbar navbar-expand-sm justify-content-center " >
    <div class="navbar-nav flex-row justify-content-between w-100" id="history">   
      <div id="historyNavigator" ></div>
    </div>
  </div>

<!-- Search Buttons -->
<section class="d-flex justify-content-center  mb-3 w-100 ">
  <div class="search-bar row align-items-center w-100">
    <div class="align-items-center w-100">

      <div class="search-buttons d-flex justify-content-between">
        <button class="btn btn-outline-dark btn-lg mr-2" 
          onclick={toggleFiltering()}>
          <i class="fa-solid fa-filter"></i> FILTER
        </button>

        <p class="mb-0" id="filter-count"></p>

        <div class="dropdown">
          <button class="btn btn-outline-dark btn-lg dropdown-toggle sort-text" 
            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            SORT BY
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
            <div class="dropdown-item" onclick="applySorting('A to Z')">A to Z</div>
            <div class="dropdown-item" onclick="applySorting('Z to A')">Z to A</div>
            <div class="dropdown-item" onclick="applySorting('Price: Low to High')">Price: Low to High</div>
            <div class="dropdown-item" onclick="applySorting('Price: High to Low')">Price: High to Low</div>
          </div>
        </div>

    </div>

  </div>
</section>

<!-- Product cards  -->
<section class="product d-flex justify-content-center w-100 pt-xl-3 pb-xl-4" >
  <div class="product-wrapper d-flex justify-content-center w-100">
    <div class="product-container w-100">

  {% for product in products %}
    <a class="product-card" href={{ url_for('views.product_details', product_id=product.id) }} 
      data-origin="{{product.is_blend}}" 
      data-notes="{{product.notes}}" 
      data-location="{{product.origin}}"
      onclick="userClicksAnchor('/product/' + '{{product.id}}', '{{product.name}}')">
      <div class="product-card__img">
        <img class="w-100" src="{{url_for('static', filename=product.image )}}" alt="product image">
      </div>
      <div class="product-wrapper__card__descr p-3 w-100">
        <p class="mb-1 price">FROM ${{ product.price | format(precision=2) }}</p> 
        <h3>{{ product.name }}</h3>
        <p>{{ product.aroma }}</p>
      </div>
    </a>
  {% endfor %}

    </div>
  </div>
</section>


<!-- Filter modal -->
<div class="fixed-top w-100 h-100 filter d-flex mr-100">
  <div class="filter__wrapper d-flex justify-content-center align-items-center w-100 h-100">
    <div class="filter__container w-100 h-100 p-5">

      <div class="filter__container__header d-flex justify-content-between align-items-center w-100">
        <h2 class="m-0">Filter</h2>
        <button class="btn btn-outline-dark btn-lg " id="clear-btn" onclick={clearFiltering()}>
          Clear
        </button>
      </div>

      <div class="filter__container__body w-100 mt-5">
        <div class="filter__container__body__options w-100">

          <div class="filter__container__body__options__item w-100 mt-5">
            <h4>COFFEE TYPE</h4>
            <div class="filter__container__body__options__item__buttons d-flex w-100">
              {% for blend in blends %}
              <button class="btn btn-outline-dark btn-lg filter-btn"   
                onclick="filterProducts(this, 'blend')" id="{{blend}}">
                {{ blend }}
              </button>
              {% endfor %}
            </div>
          </div>

          <div class="filter__container__body__options__item w-100 mt-5">
            <h4>TASTE NOTES</h4>
            <div class="filter__container__body__options__item__buttons d-flex w-100">
              {% for taste in tastes %}
              <button class="btn btn-outline-dark btn-lg filter-btn"   
                onclick="filterProducts(this, 'taste')" id="{{taste}}">
                {{ taste }}
              </button>
              {% endfor %}
            </div>
          </div>

          <div class="filter__container__body__options__item w-100 mt-5">
            <h4>ORIGIN</h4>
            <div class="filter__container__body__options__item__buttons d-flex w-100">
              {% for origin in origins %}
              <button class="btn btn-outline-dark btn-lg filter-btn"   
                onclick="filterProducts(this, 'origin')" id="{{origin}}">
                {{ origin }}
              </button> 
              {% endfor %}
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  <!-- create X to move window left -->
  <div class="filter__close mt-5">
    <button class="btn btn-outline-dark btn-lg w-100 h-100 d-flex align-items-center" onclick={showFiltering()}>
      <i class="fa-solid fa-xmark"></i>
    </button>
  </div>
  <div onclick="exitFilter()" id="exitFilter"></div>



{% endblock %}

brewtiful/templates/order-completion.html
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/checkout.css') }}">
  <title>Order complete!</title>
{% endblock %}

{% extends 'base.html' %}

{% block content %}

<div class="container mt-5 mx-auto">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <h1 class="text-center">Order #{{order_id}} </h1>
      <p  class="text-center mb-5">Thank you for your order. We will be in touch soon.</p>
      <h5 class="text-center ">Order Details</h5>

      <div class="col-md-12">
        <div class="text-center" style="display: flex; flex-direction: column; justify-content: center;">
          <div class="text-center">
            <span><strong>First Name:</strong> {{ address.firstname }}</span>
          </div>
          <div class="text-center">
            <span><strong>Last Name:</strong> {{ address.surname }}</span>
          </div>  
          <div class="text-center">
            <span><strong>Address:</strong> {{ address.street }}</span>
          </div>
          <div class="text-center">
            <span><strong>Suburb:</strong> {{ address.suburb }}</span>
          </div>
          <div class="text-center">
            <span><strong>Country:</strong> {{ address.country }}</span>
          </div>
          <div class="text-center">
            <span><strong>Postcode:</strong> {{ address.postcode }}</span>
          </div>
          <div class="text-center">
            <span><strong>Phone:</strong> {{ address.phone }}</span>
          </div>
          <div class="text-center">
            <span><strong>Email:</strong> {{ address.email }}</span>
          </div>
      </div>

      <ul class="mt-4"> 
        <p>Items: {{ products.length }}</p>
        {% for product in products %}
        <li class="d-flex mb-4 pb-4 review-product">
          <div class="">
            <img src="{{ url_for('static', filename=product.image) }}" alt="product image" class="img-fluid " id="review-img">
          </div>
          <div class="review-text">
            <div class="row mb-4">
              <div class="col-3">
                <p>{{product.name}}</p> <!-- This all needs to be a for looop-->
                <p><span id="price">AU {{product.price }}</span></p> <!-- make currecy format-->
              </div>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <a  href="{{ url_for('views.index') }}" class="btn btn-secondary mb-5">Return home</a>
    </div>
  </div>
</div>
  
{% endblock %}

brewtiful/templates/product-details.html
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/product-details.css') }}">
  <title>{{ product.name }}: Details</title>
  <script src="{{ url_for('static', filename='js/dumbEventListenerForProductPage.js') }}"></script>
{% endblock %} 

{% extends 'base.html' %}

{% block content %}
<div class="navbar navbar-expand-sm justify-content-center " >
  <div class="navbar-nav flex-row justify-content-between w-100" id="history">   
    <div id="historyNavigator" ></div>
  </div>
</div>
<section class="container mt-4 mb-5">

  <div class="row">
    <div class="col-lg-8 product-img">
      <!-- Product Image -->
  <img src={{url_for('static', filename=product.image )}} alt="Product Image" class="">
    </div>

    <!-- Product Information -->
    <div class="col-lg-4 details">
      <p class="px-2 mt-2"><strong>Price:</strong> ${{ product.price }} +</p>

      <h1 class="mb-4 p-2">{{ product.name }}</h1>

      <!-- Add to Cart button -->
      <form action="{{ url_for('views.add_to_cart', product_id=product.id) }}" method="POST" id="product-form">

        <!-- select size -->
        <p class="px-2 mb-0" data-size="{{ product.size }}">Size: {{ product.size}} - ${{ product.price }}</p>

        <!-- enter quantity -->
        <p class="p-2 mb-0">Quantity</p>
        <div class="input-group mb-3">
          <input type="number" class="form-control text-left" value="1" placeholder="" id="quantity" disabled
          aria-label="Example text with button addon" aria-describedby="button-addon1" onchange="calculateCost()">
        </div>

        <span id="total"></span>

        <!-- add to cart button -->
        <span id="total"></span>
          <input type="hidden" name="quantity" id="quantity-input" value="{{ request.form.get('quantity') or 1 }}">
          <button class="btn-secondary" type="submit" onclick="handleFormSubmit()"
            >Add to Cart
          </button> <!-- SHOULD I ADD A ADDED TO CART SUCCESS WINDOW -->
      </form>

      <!-- description -->
      <p class="secondary mb-0 p-2">{{ product.description }}</p>

      <div class="m-0 stamps">
        <div>
          {% if product.is_blend %}
            Blend
          {% else %}
            Single origin
          {% endif %}
        </div>
        <div>{{ product.origin}}</div>
      </div>
    </div>
  </div>
</section>

{% endblock %}